/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TeacherQuizRouteImport } from './routes/teacher-quiz'
import { Route as TeacherLessonRouteImport } from './routes/teacher-lesson'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as QuizRouteImport } from './routes/quiz'
import { Route as QrRouteImport } from './routes/qr'
import { Route as PeersRouteImport } from './routes/peers'
import { Route as LessonRouteImport } from './routes/lesson'
import { Route as GetStartedRouteImport } from './routes/get-started'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CoursesRouteImport } from './routes/courses'
import { Route as AdminQuizRouteImport } from './routes/admin-quiz'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as DashboardPerformanceRouteImport } from './routes/dashboard.performance'
import { Route as DashboardPeersRouteImport } from './routes/dashboard.peers'
import { Route as DashboardNotificationsRouteImport } from './routes/dashboard.notifications'
import { Route as DashboardCoursesRouteImport } from './routes/dashboard.courses'

const TeacherQuizRoute = TeacherQuizRouteImport.update({
  id: '/teacher-quiz',
  path: '/teacher-quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherLessonRoute = TeacherLessonRouteImport.update({
  id: '/teacher-lesson',
  path: '/teacher-lesson',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizRoute = QuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const QrRoute = QrRouteImport.update({
  id: '/qr',
  path: '/qr',
  getParentRoute: () => rootRouteImport,
} as any)
const PeersRoute = PeersRouteImport.update({
  id: '/peers',
  path: '/peers',
  getParentRoute: () => rootRouteImport,
} as any)
const LessonRoute = LessonRouteImport.update({
  id: '/lesson',
  path: '/lesson',
  getParentRoute: () => rootRouteImport,
} as any)
const GetStartedRoute = GetStartedRouteImport.update({
  id: '/get-started',
  path: '/get-started',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesRoute = CoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminQuizRoute = AdminQuizRouteImport.update({
  id: '/admin-quiz',
  path: '/admin-quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPerformanceRoute = DashboardPerformanceRouteImport.update({
  id: '/performance',
  path: '/performance',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPeersRoute = DashboardPeersRouteImport.update({
  id: '/peers',
  path: '/peers',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardNotificationsRoute = DashboardNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCoursesRoute = DashboardCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin-quiz': typeof AdminQuizRoute
  '/courses': typeof CoursesRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/get-started': typeof GetStartedRoute
  '/lesson': typeof LessonRoute
  '/peers': typeof PeersRoute
  '/qr': typeof QrRoute
  '/quiz': typeof QuizRoute
  '/signin': typeof SigninRoute
  '/teacher-lesson': typeof TeacherLessonRoute
  '/teacher-quiz': typeof TeacherQuizRoute
  '/dashboard/courses': typeof DashboardCoursesRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/peers': typeof DashboardPeersRoute
  '/dashboard/performance': typeof DashboardPerformanceRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin-quiz': typeof AdminQuizRoute
  '/courses': typeof CoursesRoute
  '/get-started': typeof GetStartedRoute
  '/lesson': typeof LessonRoute
  '/peers': typeof PeersRoute
  '/qr': typeof QrRoute
  '/quiz': typeof QuizRoute
  '/signin': typeof SigninRoute
  '/teacher-lesson': typeof TeacherLessonRoute
  '/teacher-quiz': typeof TeacherQuizRoute
  '/dashboard/courses': typeof DashboardCoursesRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/peers': typeof DashboardPeersRoute
  '/dashboard/performance': typeof DashboardPerformanceRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin-quiz': typeof AdminQuizRoute
  '/courses': typeof CoursesRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/get-started': typeof GetStartedRoute
  '/lesson': typeof LessonRoute
  '/peers': typeof PeersRoute
  '/qr': typeof QrRoute
  '/quiz': typeof QuizRoute
  '/signin': typeof SigninRoute
  '/teacher-lesson': typeof TeacherLessonRoute
  '/teacher-quiz': typeof TeacherQuizRoute
  '/dashboard/courses': typeof DashboardCoursesRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/peers': typeof DashboardPeersRoute
  '/dashboard/performance': typeof DashboardPerformanceRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin-quiz'
    | '/courses'
    | '/dashboard'
    | '/get-started'
    | '/lesson'
    | '/peers'
    | '/qr'
    | '/quiz'
    | '/signin'
    | '/teacher-lesson'
    | '/teacher-quiz'
    | '/dashboard/courses'
    | '/dashboard/notifications'
    | '/dashboard/peers'
    | '/dashboard/performance'
    | '/dashboard/settings'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin-quiz'
    | '/courses'
    | '/get-started'
    | '/lesson'
    | '/peers'
    | '/qr'
    | '/quiz'
    | '/signin'
    | '/teacher-lesson'
    | '/teacher-quiz'
    | '/dashboard/courses'
    | '/dashboard/notifications'
    | '/dashboard/peers'
    | '/dashboard/performance'
    | '/dashboard/settings'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/admin-quiz'
    | '/courses'
    | '/dashboard'
    | '/get-started'
    | '/lesson'
    | '/peers'
    | '/qr'
    | '/quiz'
    | '/signin'
    | '/teacher-lesson'
    | '/teacher-quiz'
    | '/dashboard/courses'
    | '/dashboard/notifications'
    | '/dashboard/peers'
    | '/dashboard/performance'
    | '/dashboard/settings'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminQuizRoute: typeof AdminQuizRoute
  CoursesRoute: typeof CoursesRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  GetStartedRoute: typeof GetStartedRoute
  LessonRoute: typeof LessonRoute
  PeersRoute: typeof PeersRoute
  QrRoute: typeof QrRoute
  QuizRoute: typeof QuizRoute
  SigninRoute: typeof SigninRoute
  TeacherLessonRoute: typeof TeacherLessonRoute
  TeacherQuizRoute: typeof TeacherQuizRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/teacher-quiz': {
      id: '/teacher-quiz'
      path: '/teacher-quiz'
      fullPath: '/teacher-quiz'
      preLoaderRoute: typeof TeacherQuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher-lesson': {
      id: '/teacher-lesson'
      path: '/teacher-lesson'
      fullPath: '/teacher-lesson'
      preLoaderRoute: typeof TeacherLessonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz': {
      id: '/quiz'
      path: '/quiz'
      fullPath: '/quiz'
      preLoaderRoute: typeof QuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qr': {
      id: '/qr'
      path: '/qr'
      fullPath: '/qr'
      preLoaderRoute: typeof QrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/peers': {
      id: '/peers'
      path: '/peers'
      fullPath: '/peers'
      preLoaderRoute: typeof PeersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lesson': {
      id: '/lesson'
      path: '/lesson'
      fullPath: '/lesson'
      preLoaderRoute: typeof LessonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/get-started': {
      id: '/get-started'
      path: '/get-started'
      fullPath: '/get-started'
      preLoaderRoute: typeof GetStartedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses': {
      id: '/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-quiz': {
      id: '/admin-quiz'
      path: '/admin-quiz'
      fullPath: '/admin-quiz'
      preLoaderRoute: typeof AdminQuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/performance': {
      id: '/dashboard/performance'
      path: '/performance'
      fullPath: '/dashboard/performance'
      preLoaderRoute: typeof DashboardPerformanceRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/peers': {
      id: '/dashboard/peers'
      path: '/peers'
      fullPath: '/dashboard/peers'
      preLoaderRoute: typeof DashboardPeersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/notifications': {
      id: '/dashboard/notifications'
      path: '/notifications'
      fullPath: '/dashboard/notifications'
      preLoaderRoute: typeof DashboardNotificationsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/courses': {
      id: '/dashboard/courses'
      path: '/courses'
      fullPath: '/dashboard/courses'
      preLoaderRoute: typeof DashboardCoursesRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardCoursesRoute: typeof DashboardCoursesRoute
  DashboardNotificationsRoute: typeof DashboardNotificationsRoute
  DashboardPeersRoute: typeof DashboardPeersRoute
  DashboardPerformanceRoute: typeof DashboardPerformanceRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardCoursesRoute: DashboardCoursesRoute,
  DashboardNotificationsRoute: DashboardNotificationsRoute,
  DashboardPeersRoute: DashboardPeersRoute,
  DashboardPerformanceRoute: DashboardPerformanceRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminQuizRoute: AdminQuizRoute,
  CoursesRoute: CoursesRoute,
  DashboardRoute: DashboardRouteWithChildren,
  GetStartedRoute: GetStartedRoute,
  LessonRoute: LessonRoute,
  PeersRoute: PeersRoute,
  QrRoute: QrRoute,
  QuizRoute: QuizRoute,
  SigninRoute: SigninRoute,
  TeacherLessonRoute: TeacherLessonRoute,
  TeacherQuizRoute: TeacherQuizRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
